#FROM node:20-alpine as build
#WORKDIR /app
#COPY package*.json ./
#RUN npm install -g @angular/cli
#RUN npm install
#COPY . .
#RUN npm run build
FROM nginx:1.25.3-alpine
COPY dist/angular-16-crud/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]