name: 'Build Maven app'
description: 'Steps for building Maven app'
inputs:
  directory:  
    description: 'spring boot app directory'
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: cd ${{ inputs.directory }} && mvn -B package 
      shell: bash 