name: 'Extract Docker Image Version'
description: 'Steps for extracting Docker image version'
inputs:
  commit-message:
    description: 'Commit message containing version information'
    default: 'version:latest'
runs:
  using: "composite"
  steps:
    - name: Extract Docker Image Version
      id: extract-version
      run: |
        version=$(echo "${{ inputs.commit-message }}" | grep -oP 'version:\s*([\d.]+)')
        version=${version#version:}
        echo "Docker Image Version: $version"
        echo "version=$version" >> $GITHUB_ENV
      shell: bash
